// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cgcvnkcboqyunfxzjbcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnY3Zua2Nib3F5dW5meHpqYmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNTc3MzgsImV4cCI6MjA3NjYzMzczOH0.nd6IWbr-Y5RlNgTjU_Rx2jSy9YMGJx6l8vLeBikcGFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);